- hosts: remote
  vars_prompt:
          - name : src
            prompt: "Quelle est la source du fichier ?"
            private: no

          - name : dest
            prompt: "Quelle est la destination du fichier ?"
            private: no

  tasks:
  - name: copy file to remote server
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"